// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WebService
{
    public partial class InventoryCountHistoryDatum
    {
        public int Id { get; set; }
        public string Product { get; set; }
        public int Amount { get; set; }
        public int InventoryCountHistory { get; set; }

        public virtual InventoryCountHistory InventoryCountHistoryNavigation { get; set; }
    }
}