// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WebService
{
    public partial class OrderHistoryDatum
    {
        public int Id { get; set; }
        public int OrderHistory { get; set; }
        public string Product { get; set; }
        public int MissingAmount { get; set; }
        public int AmountPerBox { get; set; }
        public int RecommendedAmount { get; set; }
        public int AmountOrdered { get; set; }
        public string Supplier { get; set; }

        public virtual OrderHistory OrderHistoryNavigation { get; set; }
    }
}